# This is a basic workflow to help you get started with Actions

name: CI





# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: 
      - 'v*.*'
      - 'v**.*'
      - 'v*.**'
      - '!v*.*-beta'
      - '!v0.*.*'
      - '!feature-**'
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '#NORUN') }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Compute Tag Name
        id: compute-tag
        run: |
          BRANCH_NAME=$(git branch --show-current) #2 (Explanation)
          VERSION_NAME=$(basename $BRANCH_NAME) #3 (Explanation)
          echo "tagname=${VERSION_NAME}" >> $GITHUB_OUTPUT #4 (Explanation)

      - name: Build
        run: echo ${{ steps.compute-tag.outputs.tagname }} >> ./release_file.txt #5 (Explanation)

      - name: Create release
        uses: actions/create-release@v1
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.compute-tag.outputs.tagname }}
          release_name: ${{ steps.compute-tag.outputs.tagname }}
          draft: false
          prerelease: false
  
      

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
